from utils import utc_now_iso
from state_manager import write_per_run_report, write_run_report


def build_run_report(
    run_id: str,
    mode: str,
    result: str,
    reason: str,
    trigger_source: str,
    side: str,
    symbol: str,
    qty: int,
    openclaw_enabled: bool,
    duplicate_cooldown_seconds: int,
    max_position_size: int,
    allowed_symbols: list[str],
    alpaca_base_url: str,
    signal_timeframe=None,
    signal_limit=None,
    buying_power=None,
    estimated_cost=None,
    duplicate_age_seconds=None,
    order_status=None,
    submit_state=None,
    reconciliation_status=None,
    manual_review_required=None,
    terminal_for_run=None,
    reconciliation_ambiguous=None,
    filled_qty=None,
    working_qty=None,
    notes=None,
    existing_position_qty=None,
    open_buy_order_qty=None,
    projected_position_qty=None,
    orchestration=None,
    ibkr_runtime=None,
) -> dict:
    return {
        "run_id": run_id,
        "timestamp": utc_now_iso(),
        "trigger_source": trigger_source,
        "result": result,
        "reason": reason,
        "symbol": symbol,
        "side": side,
        "qty": qty,
        "mode": mode,
        "openclaw_enabled": openclaw_enabled,
        "cooldown_seconds": duplicate_cooldown_seconds,
        "max_position_size": max_position_size,
        "allowed_symbols": allowed_symbols,
        "alpaca_base_url": alpaca_base_url,
        "signal_timeframe": signal_timeframe,
        "signal_limit": signal_limit,
        "buying_power": buying_power,
        "estimated_cost": estimated_cost,
        "duplicate_age_seconds": duplicate_age_seconds,
        "order_status": order_status,
        "submit_state": submit_state,
        "reconciliation_status": reconciliation_status,
        "manual_review_required": manual_review_required,
        "terminal_for_run": terminal_for_run,
        "reconciliation_ambiguous": reconciliation_ambiguous,
        "filled_qty": filled_qty,
        "working_qty": working_qty,
        "existing_position_qty": existing_position_qty,
        "open_buy_order_qty": open_buy_order_qty,
        "projected_position_qty": projected_position_qty,
        "orchestration": orchestration,
        "ibkr_runtime": ibkr_runtime,
        "notes": notes or [],
    }


def persist_report(
    run_id: str,
    mode: str,
    result: str,
    reason: str,
    trigger_source: str,
    side: str,
    symbol: str,
    qty: int,
    openclaw_enabled: bool,
    duplicate_cooldown_seconds: int,
    max_position_size: int,
    allowed_symbols: list[str],
    alpaca_base_url: str,
    run_report_file: str,
    signal_timeframe=None,
    signal_limit=None,
    buying_power=None,
    estimated_cost=None,
    duplicate_age_seconds=None,
    order_status=None,
    submit_state=None,
    reconciliation_status=None,
    manual_review_required=None,
    terminal_for_run=None,
    reconciliation_ambiguous=None,
    filled_qty=None,
    working_qty=None,
    notes=None,
    existing_position_qty=None,
    open_buy_order_qty=None,
    projected_position_qty=None,
    orchestration=None,
    ibkr_runtime=None,
) -> None:
    report = build_run_report(
        run_id=run_id,
        mode=mode,
        result=result,
        reason=reason,
        trigger_source=trigger_source,
        side=side,
        symbol=symbol,
        qty=qty,
        openclaw_enabled=openclaw_enabled,
        duplicate_cooldown_seconds=duplicate_cooldown_seconds,
        max_position_size=max_position_size,
        allowed_symbols=allowed_symbols,
        alpaca_base_url=alpaca_base_url,
        signal_timeframe=signal_timeframe,
        signal_limit=signal_limit,
        buying_power=buying_power,
        estimated_cost=estimated_cost,
        duplicate_age_seconds=duplicate_age_seconds,
        order_status=order_status,
        submit_state=submit_state,
        reconciliation_status=reconciliation_status,
        manual_review_required=manual_review_required,
        terminal_for_run=terminal_for_run,
        reconciliation_ambiguous=reconciliation_ambiguous,
        filled_qty=filled_qty,
        working_qty=working_qty,
        notes=notes,
        existing_position_qty=existing_position_qty,
        open_buy_order_qty=open_buy_order_qty,
        projected_position_qty=projected_position_qty,
        orchestration=orchestration,
        ibkr_runtime=ibkr_runtime,
    )
    write_run_report(report, run_report_file)
    write_per_run_report(report, run_report_file)
