from utils import utc_now_iso
from state_manager import write_run_report_for_settings


def build_run_report_for_settings(
    settings,
    run_id: str,
    mode: str,
    result: str,
    reason: str,
    trigger_source: str,
    side: str,
    buying_power=None,
    estimated_cost=None,
    duplicate_age_seconds=None,
    order_status=None,
    notes=None,
    existing_position_qty=None,
    open_buy_order_qty=None,
    projected_position_qty=None,
) -> dict:
    return {
        "run_id": run_id,
        "timestamp": utc_now_iso(),
        "trigger_source": trigger_source,
        "result": result,
        "reason": reason,
        "symbol": settings.symbol,
        "side": side,
        "qty": settings.qty,
        "mode": mode,
        "openclaw_enabled": settings.openclaw_enabled,
        "cooldown_seconds": settings.duplicate_cooldown_seconds,
        "max_position_size": settings.max_position_size,
        "allowed_symbols": list(settings.allowed_symbols),
        "alpaca_base_url": settings.alpaca_base_url,
        "buying_power": buying_power,
        "estimated_cost": estimated_cost,
        "duplicate_age_seconds": duplicate_age_seconds,
        "order_status": order_status,
        "existing_position_qty": existing_position_qty,
        "open_buy_order_qty": open_buy_order_qty,
        "projected_position_qty": projected_position_qty,
        "notes": notes or [],
    }


def persist_report_for_settings(
    settings,
    run_id: str,
    mode: str,
    result: str,
    reason: str,
    trigger_source: str,
    side: str,
    buying_power=None,
    estimated_cost=None,
    duplicate_age_seconds=None,
    order_status=None,
    notes=None,
    existing_position_qty=None,
    open_buy_order_qty=None,
    projected_position_qty=None,
) -> None:
    report = build_run_report_for_settings(
        settings=settings,
        run_id=run_id,
        mode=mode,
        result=result,
        reason=reason,
        trigger_source=trigger_source,
        side=side,
        buying_power=buying_power,
        estimated_cost=estimated_cost,
        duplicate_age_seconds=duplicate_age_seconds,
        order_status=order_status,
        notes=notes,
        existing_position_qty=existing_position_qty,
        open_buy_order_qty=open_buy_order_qty,
        projected_position_qty=projected_position_qty,
    )
    write_run_report_for_settings(settings, report)
